#!/usr/bin/env python3
"""Run the locked patient-level longitudinal public-data extension."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

MODULE_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(MODULE_ROOT))

from longitudinal_extension.analysis import (  # noqa: E402
    add_gse162975_stage_aliases,
    analyze_contrasts,
    analyze_marker_contrasts,
    leave_one_out,
    summarize_gse197268_product_strata,
    summarize_markers,
    summarize_samples,
)
from longitudinal_extension.common import holm_adjust  # noqa: E402
from longitudinal_extension.constants import DEFAULT_SEED  # noqa: E402
from longitudinal_extension.output import assert_finite_results, write_outputs  # noqa: E402
from longitudinal_extension.parsers import (  # noqa: E402
    build_gse197268_screening,
    parse_gse162975_matrix,
    parse_gse197268_archives,
    parse_gse235760_h5ad,
    parse_gse273170_archive,
    read_standard_cells,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--gse197268-dir", type=Path)
    parser.add_argument(
        "--gse197268-obs",
        type=Path,
        default=Path("data/raw/GSE197268/Fig1_CART_global_obs.csv"),
    )
    parser.add_argument(
        "--gse197268-subtype",
        type=Path,
        default=Path("data/raw/GSE197268/Fig2_ALLT_CD_classifications.txt"),
    )
    parser.add_argument(
        "--gse197268-crosswalk",
        type=Path,
        default=Path("config/gse197268_sample_crosswalk.tsv"),
    )
    parser.add_argument("--gse162975-matrix", type=Path)
    parser.add_argument(
        "--gse162975-crosswalk",
        type=Path,
        default=Path("config/gse162975_technical_crosswalk.tsv"),
    )
    parser.add_argument(
        "--gse162975-stage-aliases",
        type=Path,
        default=Path("config/gse162975_crosswalk.tsv"),
    )
    parser.add_argument("--gse235760-h5ad", type=Path)
    parser.add_argument("--gse273170-archive", type=Path)
    parser.add_argument(
        "--gse273170-crosswalk",
        type=Path,
        default=Path("config/gse273170_crosswalk.tsv"),
    )
    parser.add_argument(
        "--source-manifest",
        type=Path,
        default=Path("config/longitudinal_sources.tsv"),
        help="Checksum-pinned inventory used to retrieve public source files",
    )
    parser.add_argument(
        "--standard-cells",
        type=Path,
        action="append",
        default=[],
        help="Additional lossless cell tables generated by audited cohort adapters",
    )
    parser.add_argument("--contrasts", type=Path, default=Path("config/longitudinal_contrasts.tsv"))
    parser.add_argument(
        "--output-dir", type=Path, default=Path("results/longitudinal_extension/local")
    )
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    frames: list[pd.DataFrame] = []
    gse197268_screening: pd.DataFrame | None = None
    input_paths = [args.contrasts]
    if args.gse197268_dir:
        gse197268_screening = build_gse197268_screening(args.gse197268_obs, args.gse197268_subtype)
        frames.append(
            parse_gse197268_archives(
                args.gse197268_dir,
                args.gse197268_obs,
                args.gse197268_subtype,
                args.gse197268_crosswalk,
            )
        )
        gse197268_crosswalk = pd.read_csv(
            args.gse197268_crosswalk, sep="\t", dtype=str, keep_default_na=False
        )
        selected_patients = set(gse197268_crosswalk["patient_id"])
        screened_patients = set(
            gse197268_screening.loc[gse197268_screening["included_at_min25"].eq(1), "patient_id"]
        )
        if selected_patients != screened_patients:
            raise ValueError("GSE197268 downloaded bundles do not match the denominator screen")
        input_paths.extend(
            [
                args.gse197268_obs,
                args.gse197268_subtype,
                args.gse197268_crosswalk,
                *(
                    args.gse197268_dir / source_file
                    for source_file in gse197268_crosswalk["source_file"]
                ),
            ]
        )
    if args.gse162975_matrix:
        frames.append(parse_gse162975_matrix(args.gse162975_matrix, args.gse162975_crosswalk))
        input_paths.extend(
            [args.gse162975_matrix, args.gse162975_crosswalk, args.gse162975_stage_aliases]
        )
    if args.gse235760_h5ad:
        frames.append(parse_gse235760_h5ad(args.gse235760_h5ad))
        input_paths.append(args.gse235760_h5ad)
    if args.gse273170_archive:
        frames.append(parse_gse273170_archive(args.gse273170_archive, args.gse273170_crosswalk))
        input_paths.extend([args.gse273170_archive, args.gse273170_crosswalk])
    for path in args.standard_cells:
        frames.append(read_standard_cells(path))
        input_paths.append(path)
    if not frames:
        raise SystemExit("No cell-level inputs were supplied")
    cells = pd.concat(frames, ignore_index=True, sort=False)
    samples = summarize_samples(cells)
    markers = summarize_markers(cells)
    if cells["dataset"].eq("GSE162975").any():
        if args.gse162975_stage_aliases not in input_paths:
            input_paths.append(args.gse162975_stage_aliases)
        stage_aliases = pd.read_csv(
            args.gse162975_stage_aliases, sep="\t", dtype=str, keep_default_na=False
        )
        samples = add_gse162975_stage_aliases(samples, stage_aliases)
        markers = add_gse162975_stage_aliases(markers, stage_aliases)
    contrasts = pd.read_csv(args.contrasts, sep="\t", keep_default_na=False)
    analyzed_contrasts = contrasts[contrasts["dataset"].isin(samples["dataset"])].copy()
    inclusion, results = analyze_contrasts(samples, analyzed_contrasts)
    early = results["family_id"].eq("early_cxcr6_fraction_three_cohort")
    if int(early.sum()) != 3:
        raise ValueError("The finalized early family must contain exactly three cohort summaries")
    results.loc[early, "holm_p"] = holm_adjust(results.loc[early, "sign_test_p"])
    results = results.sort_values(["dataset", "contrast"], kind="mergesort").reset_index(drop=True)
    assert_finite_results(results)
    marker_results = analyze_marker_contrasts(markers, inclusion)
    audit_tables: dict[str, pd.DataFrame] = {}
    if gse197268_screening is not None:
        audit_tables["gse197268_screening_exclusions.tsv"] = gse197268_screening
        audit_tables["gse197268_product_stratified_results.tsv"] = (
            summarize_gse197268_product_strata(inclusion)
        )
    code_paths = sorted((MODULE_ROOT / "longitudinal_extension").glob("*.py"))
    code_paths.append(Path(__file__))
    write_outputs(
        args.output_dir,
        samples=samples,
        markers=markers,
        inclusion=inclusion,
        results=results,
        marker_results=marker_results,
        leave_one_out=leave_one_out(inclusion),
        input_paths=input_paths,
        code_paths=code_paths,
        seed=args.seed,
        manifest_root=MODULE_ROOT,
        source_manifest_path=args.source_manifest,
        audit_tables=audit_tables,
    )


if __name__ == "__main__":
    main()
